<?php
DEFINE(REM_DUPL_CONT_DEFAULT_REPLACE,'<noindex>You are watching comments page. If you want to see the whole post text, please, go LINK_BEGIN here LINK_END.</noindex>');
DEFINE(REM_DUPL_CONT_HOMEPAGE,'Plugin Homepage');
DEFINE(REM_DUPL_CONT_FEEDBACK,'Feedback');
DEFINE(REM_DUPL_CONT_TEXT,'Customize text which you want to show on comments page instead of post text. Use "LINK_BEGIN" and "LINK_END" to define the beginning and the end of link to original post text.');
?>