<?php
DEFINE(REM_DUPL_CONT_DEFAULT_REPLACE,'Вы просматриваете страницу комментариев. Если вы хотите просмореть сам текст поста, пожалуйста, перейдите LINK_BEGIN сюда LINK_END.');
DEFINE(REM_DUPL_CONT_HOMEPAGE,'Страница плагина');
DEFINE(REM_DUPL_CONT_FEEDBACK,'Отзывы');
DEFINE(REM_DUPL_CONT_TEXT,'Укажите текст, который вы хотите видеть на странице комментариев вместо текста поста. Используйте "LINK_BEGIN" и "LINK_END", чтобы указать начало и конец ссылки на текст поста.');
?>